install: npm install
language: node_js
node_js:
  - "13"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build:prod
# after_script:
# - npm install -g surge
# - sh deploy/deploy.sh
