version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: rock-app-elasticsearch
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    restart: unless-stopped
volumes:
  elasticsearch-data:
    driver: local
